### ISSUE TITLE
CustomPermissionEvaluator with @RefreshScope annotation

### ISSUE THREAD

**Issue by gitmykeul** [InSourceSoftware/spring-ws-examples#1]
I have a CustomPermissionEvaluator that overrides PermissionEvaluator.
This works fine but when I am annotating this class with @RefreshScope, it is no longer used and the DenyAllPermissionEvaluator is instead used.
Do you have any idea how I can make the customPermissionEvaluator work with @RefreshScope annotation. 
(I am using this @RefreshScope annotation since I want to be able to refresh the bean if the configuration changes - External config through Git)
Thank you!

**Comment by sjohnr** [comment]
I don't have a lot of experience with @RefreshScope, though I've looked at the docs a few times in relation to Spring Config Server.

I'm not sure what your code looks like exactly, but perhaps try using @RefreshScope on a separate bean that is used for configuration, instead of refreshing the `PermissionEvaluator` itself.

For example, using an @ConfigurationProperties:

```
@Configuration
@RefreshScope
@ConfigurationProperties("my.properties")
class MyProperties {
  private String value;
  ...
}

@Component
class CustomPermissionEvaluator implements PermissionEvaluator {
  @Autowired
  private MyProperties myProperties;
  ...
}
```

I'm not sure if this works, given what @RefreshScope has to do, but it might...

**Comment by gitmykeul** [comment]
This works. This seems to be a good workaround solution. 
@RefreshScope creates proxy and this leads to side effects on the bean instantiation.
Thank you Stephen.
